"""Build the TripPal skill **seed** layer from assets we already own.

Why a generator: the seed fragments must not be invented prose. Everything here comes from
three existing, reviewable sources:

1. `research/pain_points.md` §6 — the product taxonomy: 12 domains with timing, goal,
   required inputs, expected output, and the pain points each one covers.
2. `research/pain_points.md` §4 — 42 field pain points (id, title, mechanism).
3. `skill-loop/modules/demand-task-factory/out-v2/task_pack.jsonl` +
   `skill-loop/fixtures/tool_data_trippal_v2/pages.json` — which bundled authoritative pages
   each domain needs, which checks were written for it, and which required items its
   artifacts must contain.

Output (both under `skills/trippal/static/`):
- `fragments/domain/<slug>.md` — one conditional fragment per domain (the manifest axis).
- `corpus-map.json` — declarative domain -> bundled-page map, consumed by the router.

Every emitted fragment carries a SEED banner: it is an unreviewed draft, not policy.

Usage (from the repo root):
    python skill-loop/integration/pipeline/build_skill_seed.py [--check]

`--check` regenerates into memory and reports differences without writing (CI-friendly).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
PAIN = REPO / "research" / "pain_points.md"
PACK = REPO / "skill-loop" / "modules" / "demand-task-factory" / "out-v2" / "task_pack.jsonl"
PAGES = REPO / "skill-loop" / "fixtures" / "tool_data_trippal_v2" / "pages.json"
OUT = REPO / "skills" / "trippal" / "static"

# data-side scenario id -> product-facing domain slug (file name) and title language
SLUG = {
    "TP-S01": "entry",
    "TP-S02": "predeparture",
    "TP-S03": "payment",
    "TP-S04": "ticketing",
    "TP-S05": "train",
    "TP-S06": "citytransport",
    "TP-S07": "stay",
    "TP-S08": "connectivity",
    "TP-S09": "navigation",
    "TP-S10": "food",
    "TP-S11": "emergency",
    "TP-S12": "language",
}

# The dataset uses TP-S12 as a catch-all label for abstention/tool-choice cards, so its
# page list is not domain-specific. Do not map bundled pages for that domain.
CATCH_ALL = {"TP-S12"}

BANNER = (
    "<!-- SEED DRAFT - generated by skill-loop/integration/pipeline/build_skill_seed.py.\n"
    "     Sources: research/pain_points.md (taxonomy + field evidence) and dataset v2 cards.\n"
    "     Status: NOT reviewed by a human. Do not treat as policy; verify against the cited\n"
    "     authoritative page before acting. Re-run the generator after editing the sources. -->\n"
)


def expand_pain_ids(raw: str) -> list[str]:
    """§6 里的痛点列可能是区间（`P-B1~B6`、`P-D1~D3`）或逗号列表；展开成逐个 id。"""
    ids: list[str] = []
    for letter, start, end in re.findall(r"P-([A-Z])(\d+)\s*[~-]\s*(?:[A-Z])?(\d+)", raw):
        for n in range(int(start), int(end) + 1):
            ids.append(f"P-{letter}{n}")
    for single in re.findall(r"P-[A-Z]\d+", raw):
        if single not in ids:
            ids.append(single)
    # 去掉被区间覆盖掉的单个 id，保持字母+数字顺序且不重复
    out, seen = [], set()
    for pid in ids:
        if pid not in seen:
            seen.add(pid)
            out.append(pid)
    return sorted(out, key=lambda p: (p[2], int(p[3:])))


def parse_taxonomy(text: str) -> dict[str, dict]:
    """§6 table: | S01 | name | timing | goal | inputs | expected | pain ids |"""
    out: dict[str, dict] = {}
    for line in text.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 7 or not re.fullmatch(r"S\d{2}", cells[0]):
            continue
        out[f"TP-{cells[0]}"] = {
            "name": cells[1],
            "timing": cells[2],
            "goal": cells[3],
            "inputs": cells[4],
            "output": cells[5],
            "pain_ids": expand_pain_ids(cells[6]),
        }
    return out


def parse_pain_points(text: str) -> dict[str, dict]:
    """§4 entries look like: **P-A1｜title** · S1 · 覆盖 4 切片  /  - 机制：..."""
    out: dict[str, dict] = {}
    current: str | None = None
    for line in text.splitlines():
        m = re.match(r"\*\*(P-[A-Z]\d+)｜(.+?)\*\*\s*(.*)$", line.strip())
        if m:
            current = m.group(1)
            out[current] = {"title": m.group(2).strip(), "meta": m.group(3).strip(), "mechanism": ""}
            continue
        if current and line.strip().startswith("- 机制："):
            out[current]["mechanism"] = line.strip()[len("- 机制："):].strip()
            current = None
    return out


def load_cards() -> list[dict]:
    if not PACK.exists():
        return []
    return [json.loads(l) for l in PACK.read_text(encoding="utf-8").splitlines() if l.strip()]


def domain_facts(cards: list[dict]) -> dict[str, dict]:
    """Per dataset scenario: bundled pages, decision checks, required artifact items."""
    facts: dict[str, dict] = defaultdict(lambda: {"pages": [], "checks": [], "items": []})
    seen_pages: dict[str, set] = defaultdict(set)
    for c in cards:
        sid = c.get("scenario_id", "")
        if sid not in SLUG:
            continue
        f = facts[sid]
        for q in (c.get("demand_evidence") or {}).get("query_cluster") or []:
            if q not in seen_pages[sid]:
                seen_pages[sid].add(q)
                f["pages"].append(q)
        for a in (c.get("verifier") or {}).get("assertions") or []:
            note = (a.get("note") or "").strip()
            if a.get("op") != "regex" or not note:
                continue
            if "条款" in note:
                if note not in f["checks"]:
                    f["checks"].append(note)
            elif c["task_type"] == "artifact_card" and note not in f["items"]:
                # 只收内容项：长度/篇幅类要求属于 output-and-quality，不属于域内容
                if any(k in note for k in ("篇幅", "长度", "字数", "词")):
                    continue
                f["items"].append(note)
    return facts


def render_fragment(sid: str, tax: dict, pains: dict, facts: dict, pages: dict) -> str:
    slug = SLUG[sid]
    d = tax[sid]
    lines = [BANNER, f"# {d['name']}（`{slug}`）", ""]
    lines += [
        f"- **时机**：{d['timing']}",
        f"- **目标**：{d['goal']}",
        f"- **需要向旅客确认**：{d['inputs']}",
        f"- **这个域的好产出**：{d['output']}",
        "",
    ]

    f = facts.get(sid, {})
    lines += ["## 随包权威来源（拼进上下文的就是这些正文）", ""]
    if sid in CATCH_ALL:
        lines += [
            "> 该域在数据集里是 A/D/E 卡的兜底标签，没有专属随包页面；检索策略见 "
            "`references/source-policy.md`，需要时用 `static/corpus-map.json` 找相关域。",
            "",
        ]
    elif f.get("pages"):
        lines += ["| 页面 | 生效日期 |", "|---|---|"]
        for key in f["pages"]:
            p = pages.get(key, {})
            url = p.get("source_url", "(unknown)")
            date = p.get("effective_date") or "—"
            lines.append(f"| `{url}` | {date} |")
        lines.append("")
    else:
        lines += ["> 尚无随包来源，需按 `references/source-policy.md` 找外部权威。", ""]

    lines += ["## 要核对的检查项", ""]
    if f.get("checks"):
        lines += [f"- {c}" for c in f["checks"]]
    else:
        lines += ["- 按 `static/core/workflow.md` 的依赖链逐项核对，结论必须落在随包来源或外部权威上。"]
    lines.append("")

    lines += ["## 答案里必须出现的内容", ""]
    if f.get("items"):
        lines += [f"- {i}" for i in f["items"]]
    else:
        lines += ["- 该域没有清单类产物卡；按题面要求逐条覆盖，缺项要显式说明。"]
    lines.append("")

    lines += ["## 已知失败模式（调研证据，不是现行政策）", ""]
    if d["pain_ids"]:
        for pid in d["pain_ids"]:
            p = pains.get(pid)
            if not p:
                lines.append(f"- **{pid}**（原文缺失，需回 research/pain_points.md 核对）")
                continue
            mech = f"：{p['mechanism']}" if p["mechanism"] else ""
            lines.append(f"- **{pid}｜{p['title']}**{mech}")
    else:
        lines += ["- 调研未给该域编号痛点，见 `references/readiness-baseline.md`。"]
    lines += [
        "",
        "## 不要",
        "",
        "- 不要用记忆或推断补政策细节；该域的所有时限、口岸、渠道、费用都要落到随包来源或外部权威。",
        "- 不要把「看起来相关」当成「回答了问题」；来源不足时按 `static/core/output-and-quality.md` 明说不确定。",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="生成 TripPal skill seed 层（域分片 + 语料映射）")
    ap.add_argument("--check", action="store_true", help="只比对，不写盘")
    args = ap.parse_args(argv)

    text = PAIN.read_text(encoding="utf-8")
    tax = parse_taxonomy(text)
    pains = parse_pain_points(text)
    cards = load_cards()
    facts = domain_facts(cards)
    pages = json.loads(PAGES.read_text(encoding="utf-8")) if PAGES.exists() else {}

    missing = [s for s in SLUG if s not in tax]
    if missing:
        print(f"分类法缺场景：{missing}", file=sys.stderr)
        return 2

    written, changed = [], []
    for sid, slug in SLUG.items():
        body = render_fragment(sid, tax, pains, facts, pages)
        path = OUT / "fragments" / "domain" / f"{slug}.md"
        written.append(path)
        if args.check:
            old = path.read_text(encoding="utf-8") if path.exists() else ""
            if old != body + "\n":
                changed.append(str(path.relative_to(REPO)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body + "\n", encoding="utf-8")

    corpus = {
        "schema_version": "seed-1",
        "generated_by": "skill-loop/integration/pipeline/build_skill_seed.py",
        "note": (
            "domain -> bundled authoritative pages. Keys match manifest.yaml axes.domain.values. "
            "TP-S12 is a dataset catch-all label, so the language domain intentionally maps no pages."
        ),
        "domains": {},
    }
    for sid, slug in SLUG.items():
        entries = []
        for key in facts.get(sid, {}).get("pages", []):
            p = pages.get(key, {})
            entries.append({
                "page_key": key,
                "url": p.get("source_url", ""),
                "effective_date": p.get("effective_date") or None,
                "rule_id": p.get("rule_id"),
            })
        corpus["domains"][slug] = {
            "dataset_scenario": sid,
            "title": tax[sid]["name"],
            "bundled_pages": entries,
            "coverage": "none" if sid in CATCH_ALL else ("bundled" if entries else "external-only"),
        }
    cmap_path = OUT / "corpus-map.json"
    cmap_text = json.dumps(corpus, ensure_ascii=False, indent=1) + "\n"
    if args.check:
        old = cmap_path.read_text(encoding="utf-8") if cmap_path.exists() else ""
        if old != cmap_text:
            changed.append(str(cmap_path.relative_to(REPO)))
        print(f"[check] {len(written)} 个分片 + corpus-map.json，需更新的文件：{len(changed)}")
        for c in changed:
            print(f"  - {c}")
        return 1 if changed else 0
    cmap_path.write_text(cmap_text, encoding="utf-8")

    print(f"[seed] 写入 {len(written)} 个域分片 -> {OUT / 'fragments' / 'domain'}")
    print(f"[seed] 写入 corpus-map.json（{sum(len(v['bundled_pages']) for v in corpus['domains'].values())} 条页面映射）")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
